[project]
name = "casa"
version = "0.1.1"
description = "Constrained Aligned Sampling Algorithms"

readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
keywords = ["language-models", "sampling", "constrained-generation", "grammar"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
	"accelerate>=1.13.0",
    "torch>=2.11.0",
    "transformers>=5.4.0",
    "numpy>=2.4.4",
    "llguidance>=1.7.0",
    "rich>=14.3.3",
    "xgrammar>=0.1.33"
]

[project.urls]
Homepage = "https://github.com/LargeLorisModels/casa.git"
Repository = "https://github.com/LargeLorisModels/casa.git"
"Bug Tracker" = "https://github.com/LargeLorisModels/casa/issues"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.8",
]